In [13]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set(style="whitegrid")
from sklearn.linear_model import LinearRegression  # Corrected import statement
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
sns.set(style="whitegrid")
print("All libraries imported successfully.")

All libraries imported successfully.

In [2]:
df=pd.read_csv('retail_marketing_sales.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Store_ID               150 non-null    object
 1   City                   150 non-null    object
 2   Store_Area_sqft        150 non-null    int64
 3   Marketing_Spend_Lakhs  150 non-null    float64
 4   No_of_Promotions       150 non-null    int64
 5   Avg_Footfall_per_Day   150 non-null    int64
 6   Monthly_Sales_Lakhs    150 non-null    float64
dtypes: float64(2), int64(3), object(2)
memory usage: 8.3+ KB

In [4]:
df.describe()

,Store_Area_sqft,Marketing_Spend_Lakhs,No_of_Promotions,Avg_Footfall_per_Day,Monthly_Sales_Lakhs
count,150.000000,150.000000,150.000000,150.000000,150.000000
mean,1907.753333,5.104600,6.406667,374.406667,23.205867
std,657.294525,2.857604,3.645530,164.300433,10.607962
min,814.000000,0.600000,1.000000,80.000000,3.000000
25%,1344.500000,2.582500,3.000000,241.000000,14.475000
50%,1878.000000,4.875000,6.000000,360.000000,22.730000
75%,2514.500000,7.655000,10.000000,507.250000,32.215000
max,2998.000000,9.930000,12.000000,711.000000,47.130000

In [6]:
df.head(10)

,Store_ID,City,Store_Area_sqft,Marketing_Spend_Lakhs,No_of_Promotions,Avg_Footfall_per_Day,Monthly_Sales_Lakhs
0,STR001,Mumbai,914,0.72,11,185,15.06
1,STR002,Hyderabad,2656,5.48,9,419,28.83
2,STR003,Bangalore,884,7.12,12,471,29.42
3,STR004,Hyderabad,1903,4.56,8,313,17.28
4,STR005,Pune,1201,1.78,8,244,8.99
5,STR006,Bangalore,2848,3.65,9,288,20.06
6,STR007,Bangalore,1943,6.11,4,374,31.45
7,STR008,Mumbai,1942,9.44,4,608,28.85
8,STR009,Delhi,1653,9.93,8,642,46.07
9,STR010,Bangalore,1798,2.80,1,228,17.32

In [10]:
df.max()

Store_ID                 STR150
City                       Pune
Store_Area_sqft            2998
Marketing_Spend_Lakhs      9.93
No_of_Promotions             12
Avg_Footfall_per_Day        711
Monthly_Sales_Lakhs       47.13
dtype: object